const VERSION=4,KEY='chunk-solvency-v4',OLD=['chunk-solvency-v3','chunk-solvency-v2','chunk-solvency-v1'];
const A={hardAsset:['Hard assets','HARD ASSET','hard','Sellable possessions. Least liquid.'],pipeline:['Pipeline','PIPELINE','pipeline','Expected money. Not active cash until it lands.'],cash:['True cash','TRUE CASH','cash','Immediately accessible money.'],buffer:['Protected buffer','PROTECTED BUFFER','buffer','Money deliberately separated from active panic.'],investment:['Investments','INVESTMENTS','invest','Conditional liquidity with a future cost.']};
const ORDER=['hardAsset','pipeline','cash','buffer','investment']; const E={essential:['FIXED / ESSENTIAL','ess'],flexible:['VARIABLE / FLEXIBLE','flex'],oneoff:['ONE-OFF','one']};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
// State must load only after the helper consts below exist. Loading here used to call demo() before uid/n/nn/clamp had initialized.
let state,quick=null,qDraft=0,dayKey=null,dayDraft=0,editor=null,sheet=null,drag=null;
const n=(x,d=0)=>Number.isFinite(Number(x))?Number(x):d, nn=x=>Math.max(0,n(x)), clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const esc=x=>String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=x=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(nn(x));
const today=()=>{let d=new Date;return new Date(d.getFullYear(),d.getMonth(),d.getDate(),12)}; const add=(d,x)=>{let r=new Date(d);r.setDate(r.getDate()+x);return r};
const iso=d=>{d=d instanceof Date?d:new Date(`${d}T12:00:00`);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const parse=x=>/^\d{4}-\d{2}-\d{2}$/.test(x||'')?new Date(`${x}T12:00:00`):null;
const label=d=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(d), wk=d=>new Intl.DateTimeFormat('en-US',{weekday:'short'}).format(d).toUpperCase();
const tile=()=>Math.max(100,Math.round(n(state.settings.chunkSize,100)/100)*100), quarter=()=>tile()/4, cells=x=>Math.max(0,Math.round(nn(x)/quarter())), chunks=x=>{let z=cells(x)/4;return `${Number.isInteger(z)?z:z.toFixed(2).replace(/0+$/,'').replace(/\.$/,'')} chunk${z===1?'':'s'}`};
function blank(){return{version:VERSION,isDemo:false,settings:{taskPayout:0,chunkSize:100,forecastDays:28},territoryTotals:{},calendarGoals:{},assets:[],expenses:[],debts:[],desires:[]}}
function demo(){let d=today();return{version:VERSION,isDemo:true,settings:{taskPayout:66,chunkSize:100,forecastDays:28},territoryTotals:{},calendarGoals:{},assets:[{id:uid('a'),name:'Checking / active cash',type:'cash',amount:420,expectedDate:'',confidence:100,notes:''},{id:uid('a'),name:'Protected buffer',type:'buffer',amount:250,expectedDate:'',confidence:100,notes:''},{id:uid('a'),name:'Likely DA payout',type:'pipeline',amount:66,expectedDate:iso(add(d,2)),confidence:90,notes:''},{id:uid('a'),name:'Portfolio / conditional',type:'investment',amount:950,expectedDate:'',confidence:100,notes:''},{id:uid('a'),name:'Sellable misc.',type:'hardAsset',amount:130,expectedDate:'',confidence:100,notes:''}],expenses:[{id:uid('e'),name:'Rent',amount:925,cadence:'monthly',type:'essential',dueDay:add(d,9).getDate(),dueDate:'',notes:''},{id:uid('e'),name:'Insurance',amount:86,cadence:'monthly',type:'essential',dueDay:add(d,4).getDate(),dueDate:'',notes:''},{id:uid('e'),name:'Food + fuel reserve',amount:280,cadence:'monthly',type:'flexible',dueDay:add(d,14).getDate(),dueDate:'',notes:''}],debts:[{id:uid('d'),name:'Credit card',balance:9200,minPayment:263,dueDay:add(d,18).getDate(),apr:18.99,notes:''}],desires:[{id:uid('l'),name:'Hollow Press books',target:100,saved:0,notes:'Bounded book hunger.'},{id:uid('l'),name:'Tools',target:200,saved:0,notes:'Useful object accumulation.'},{id:uid('l'),name:'Candy / mystery',target:25,saved:0,notes:'A little sanctioned nonsense.'}]}}
function norm(s){s=s&&typeof s==='object'?s:blank();let tt={},go={};ORDER.forEach(k=>{if(Number.isFinite(Number(s.territoryTotals?.[k]))&&Number(s.territoryTotals[k])>=0)tt[k]=Number(s.territoryTotals[k])});Object.entries(s.calendarGoals||s.dayGoals||{}).forEach(([k,v])=>{if(/^\d{4}-\d{2}-\d{2}$/.test(k)&&nn(v)>0)go[k]=nn(v)});return{version:VERSION,isDemo:!!s.isDemo,settings:{taskPayout:nn(s.settings?.taskPayout),chunkSize:clamp(Math.round(n(s.settings?.chunkSize,100)/100)*100,100,2000),forecastDays:clamp(Math.round(n(s.settings?.forecastDays,28)/7)*7,14,84)},territoryTotals:tt,calendarGoals:go,assets:(s.assets||[]).map(x=>({id:x.id||uid('a'),name:String(x.name||'Untitled money'),type:A[x.type]?x.type:'cash',amount:nn(x.amount),expectedDate:x.expectedDate||'',confidence:clamp(n(x.confidence,100),0,100),notes:String(x.notes||'')})),expenses:(s.expenses||[]).map(x=>({id:x.id||uid('e'),name:String(x.name||'Untitled obligation'),amount:nn(x.amount),cadence:x.cadence==='oneoff'?'oneoff':'monthly',type:E[x.type]?x.type:'essential',dueDay:clamp(Math.round(n(x.dueDay,1)),1,31),dueDate:x.dueDate||'',notes:String(x.notes||'')})),debts:(s.debts||[]).map(x=>({id:x.id||uid('d'),name:String(x.name||'Untitled dragon'),balance:nn(x.balance),minPayment:nn(x.minPayment),dueDay:clamp(Math.round(n(x.dueDay,1)),1,31),apr:nn(x.apr),notes:String(x.notes||'')})),desires:(s.desires||[]).map(x=>({id:x.id||uid('l'),name:String(x.name||'Untitled track'),target:nn(x.target),saved:nn(x.saved),notes:String(x.notes||'')}))}}
function load(){try{let z=localStorage.getItem(KEY);if(z)return norm(JSON.parse(z));for(let k of OLD){z=localStorage.getItem(k);if(z)return norm(JSON.parse(z))}}catch(e){}return demo()}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}$('#saved').textContent=`SAVED LOCALLY · ${new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date())}`}
const sum=(arr,k)=>arr.reduce((s,x)=>s+nn(x[k]),0), itemTotal=t=>sum(state.assets.filter(x=>x.type===t),'amount'), hasOver=t=>Object.prototype.hasOwnProperty.call(state.territoryTotals,t), total=t=>hasOver(t)?nn(state.territoryTotals[t]):itemTotal(t), debtTotal=()=>sum(state.debts,'balance'), minTotal=()=>sum(state.debts,'minPayment'), expenseTotal=()=>sum(state.expenses.filter(x=>x.cadence==='monthly'),'amount'), wall=()=>expenseTotal()+minTotal();
function monthly(day,start,end){let out=[],m=new Date(start.getFullYear(),start.getMonth(),1,12),stop=new Date(end.getFullYear(),end.getMonth(),1,12);while(m<=stop){let z=new Date(m.getFullYear(),m.getMonth(),Math.min(day,new Date(m.getFullYear(),m.getMonth()+1,0).getDate()),12);if(z>=start&&z<=end)out.push(z);m=new Date(m.getFullYear(),m.getMonth()+1,1,12)}return out}
function events(days=state.settings.forecastDays){let start=today(),end=add(start,days-1),out=[];state.assets.filter(x=>x.type==='pipeline'&&x.expectedDate).forEach(x=>{let d=parse(x.expectedDate);if(d&&d>=start&&d<=end)out.push({source:'asset',id:x.id,kind:'income',name:x.name,amount:x.amount,effective:x.amount*x.confidence/100,date:d,meta:`${x.confidence}% confidence`})});state.expenses.forEach(x=>{let ds=x.cadence==='oneoff'?[parse(x.dueDate)].filter(Boolean):monthly(x.dueDay,start,end);ds.forEach(d=>{if(d>=start&&d<=end)out.push({source:'expense',id:x.id,kind:'expense',name:x.name,amount:x.amount,date:d,meta:x.cadence==='oneoff'?'one-off obligation':'monthly obligation'})})});state.debts.forEach(x=>monthly(x.dueDay,start,end).forEach(d=>out.push({source:'debt',id:x.id,kind:'debt',name:`${x.name} minimum`,amount:x.minPayment,date:d,meta:'debt minimum'})));return out.sort((a,b)=>a.date-b.date||(a.kind==='income'?-1:1))}
function projection(){let bal=total('cash'),breach=null;events().forEach(e=>{bal+=e.kind==='income'?e.effective:-e.amount;if(bal<0&&!breach)breach=e});return{bal,breach}}
const color={hard:'var(--hard)',pipeline:'var(--pipe)',cash:'var(--cash)',buffer:'var(--buffer)',invest:'var(--invest)',ess:'var(--ess)',flex:'var(--flex)',one:'var(--one)',debt:'var(--debt)',mass:'var(--mass)'};
function attrs(t){return `data-k="${t.k}" data-id="${t.id||''}"`}
function meta(t){if(t.k==='territory'){let a=A[t.id];return a&&{title:a[0],kicker:'LIQUIDITY TERRITORY',desc:a[3],c:a[2],label:'TERRITORY TOTAL'}}if(t.k==='expense'){let x=state.expenses.find(y=>y.id===t.id);return x&&{title:x.name,kicker:x.cadence==='monthly'?'OBLIGATION / MONTHLY':'OBLIGATION / ONE-OFF',desc:'Tune this amount directly. Its date and category stay on the named record.',c:E[x.type][1],label:'OBLIGATION AMOUNT',edit:'expense'}}if(t.k==='balance'||t.k==='minimum'){let x=state.debts.find(y=>y.id===t.id);return x&&{title:`${x.name} ${t.k==='balance'?'body':'minimum'}`,kicker:t.k==='balance'?'DRAGON BODY MASS':'MONTHLY DRAGON BITE',desc:t.k==='balance'?'Erase or add to the full balance. This is the dragon’s visible mass.':'Tune the monthly bite. It auto-populates its due date in the corridor.',c:t.k==='balance'?'mass':'debt',label:t.k==='balance'?'DEBT BALANCE':'MINIMUM PAYMENT',edit:'debt'}}if(t.k==='saved'){let x=state.desires.find(y=>y.id===t.id);return x&&{title:x.name,kicker:'SANCTIONED LIFE TRACK',desc:'Adjust the amount already set aside. The target stays intact.',c:'invest',label:'AMOUNT RESERVED',edit:'desire'}}}
function get(t){if(t.k==='territory')return total(t.id);if(t.k==='expense')return state.expenses.find(x=>x.id===t.id)?.amount||0;if(t.k==='balance')return state.debts.find(x=>x.id===t.id)?.balance||0;if(t.k==='minimum')return state.debts.find(x=>x.id===t.id)?.minPayment||0;if(t.k==='saved')return state.desires.find(x=>x.id===t.id)?.saved||0;return 0}
function set(t,v){v=nn(v);if(t.k==='territory')state.territoryTotals[t.id]=v;if(t.k==='expense'){let x=state.expenses.find(x=>x.id===t.id);if(x)x.amount=v}if(t.k==='balance'){let x=state.debts.find(x=>x.id===t.id);if(x)x.balance=v}if(t.k==='minimum'){let x=state.debts.find(x=>x.id===t.id);if(x)x.minPayment=v}if(t.k==='saved'){let x=state.desires.find(x=>x.id===t.id);if(x)x.saved=v}state.isDemo=false}
function segments(){let z=[];ORDER.forEach(t=>z.push({name:A[t][0],short:A[t][1],amount:total(t),c:A[t][2],t:{k:'territory',id:t}}));state.expenses.forEach(x=>z.push({name:x.name,short:E[x.type][0],amount:x.amount,c:E[x.type][1],t:{k:'expense',id:x.id}}));state.debts.forEach(x=>{z.push({name:`${x.name} minimum`,short:'MIN BITE',amount:x.minPayment,c:'debt',t:{k:'minimum',id:x.id}});z.push({name:`${x.name} body`,short:'DRAGON',amount:x.balance,c:'mass',t:{k:'balance',id:x.id}})});return z.filter(x=>x.amount>0)}
function renderStatus(){let next=events().find(e=>e.kind!=='income'),p=projection(),c=total('cash'),w=wall();$('#cashReadout').textContent=fmt(c);$('#monthlyReadout').textContent=fmt(w);$('#debtReadout').textContent=fmt(debtTotal());$('#taskValue').textContent=state.settings.taskPayout?fmt(state.settings.taskPayout):'—';$('#taskCopy').textContent=state.settings.taskPayout?`${chunks(state.settings.taskPayout)} enters true cash.`:'Set the usual completed-task payout.';if(next){let d=Math.max(0,Math.round((next.date-today())/86400000));$('#countdown').textContent=`T−${d}`;$('#countdownLabel').textContent=`${next.name} · ${fmt(next.amount)} · ${label(next.date)}`}else{$('#countdown').textContent='OPEN';$('#countdownLabel').textContent='No timed obligation placed yet.'}let v='The board is empty. Place the first true number and the terrain begins to exist.';if(state.assets.length||state.expenses.length||state.debts.length||Object.keys(state.territoryTotals).length){if(p.breach)v=`Active cash breaches after ${p.breach.name}. A route is needed before ${label(p.breach.date)}.`;else if(w&&c>=w)v='The baseline monthly wall is funded by true cash. Protection and acceleration are now the real questions.';else if(w)v=`True cash covers ${Math.round(c/w*100)}% of the monthly wall. The remaining gap still needs matter.`;else v='No recurring wall is defined yet. Place obligations before asking the board to forecast survival.'}$('#verdict').textContent=v;$('#demoBanner').hidden=!state.isDemo}
function renderBody(){let s=segments();$('#quantum').textContent=`${fmt(quarter())} / cell`;if(!s.length){$('#flowMap').innerHTML='';$('#bodyGrid').innerHTML='<div class="empty">No financial matter yet. Add cash, a bill, or a dragon and the continuous body appears.</div>';return}$('#flowMap').innerHTML=s.map(x=>`<button class="mapitem c-${x.c}" ${attrs(x.t)}><i></i><span><b>${esc(x.name)}</b><small>${fmt(x.amount)} · ${chunks(x.amount)}</small></span></button>`).join('');let cellsHTML=[];s.forEach(x=>{let title=`${x.name}: ${fmt(x.amount)}. Tap to tune.`;for(let i=0;i<cells(x.amount);i++)cellsHTML.push(`<button class="bodycell ${i===0?'start':''}" style="--c:${color[x.c]}" title="${esc(title)}" ${attrs(x.t)}></button>`)});$('#bodyGrid').innerHTML=cellsHTML.join('')}
function renderTime(){let start=today(),by={};events().forEach(e=>{let k=iso(e.date);(by[k]??=[]).push(e)});let html=[];for(let i=0;i<state.settings.forecastDays;i++){let d=add(start,i),k=iso(d),es=by[k]||[],g=nn(state.calendarGoals[k]);let dots=[g&&'goal',es.some(x=>x.kind==='income')&&'income',es.some(x=>x.kind==='expense')&&'bill',es.some(x=>x.kind==='debt')&&'debt'].filter(Boolean).map(x=>`<i class="${x}"></i>`).join('');html.push(`<button class="day ${i===0?'today':''}" data-day="${k}"><span class="daytop"><span><b class="daynum">DAY ${String(i+1).padStart(2,'0')}</b><small class="dayweek">${wk(d)}</small></span><strong class="daydate">${d.getDate()}</strong></span><span class="indicators">${dots}</span>${g?`<span class="daygoal">GOAL ${fmt(g)}</span>`:''}</button>`)}$('#timeGrid').innerHTML=html.join('');$('#timeStart').textContent=`${label(start)} / now`;$('#timeEnd').textContent=`${label(add(start,state.settings.forecastDays-1))} / horizon`}
function renderTerritories(){$('#territories').innerHTML=ORDER.map(t=>{let x=A[t],v=total(t);return`<button class="territory c-${x[2]}" ${attrs({k:'territory',id:t})}><span class="tk"><span>${x[1]}</span><span>${hasOver(t)?'TOTAL TUNER':'ITEM SUM'}</span></span><h3>${x[0]}</h3><strong>${fmt(v)}</strong><p>${x[3]}</p><small>${chunks(v)} · TUNE ↔</small></button>`}).join('')}
function renderExpenses(){$('#expenses').innerHTML=state.expenses.length?state.expenses.map(x=>{let d=x.cadence==='monthly'?`monthly · day ${x.dueDay}`:`one-off · ${x.dueDate?label(parse(x.dueDate)):'date needed'}`,c=E[x.type][1];return`<button class="card c-${c}" ${attrs({k:'expense',id:x.id})}><span class="ctop"><span>${E[x.type][0]}</span><span>${d}</span></span><strong class="cname">${esc(x.name)}</strong><b class="camount">${fmt(x.amount)}</b><span class="cmeta"><span>${chunks(x.amount)}</span><span>${x.cadence==='monthly'?'recurring pressure':'single impact'}</span></span><span class="hint">TAP TO TUNE ↔</span></button>`}).join(''):'<div class="empty">No obligations placed. Add rent, insurance, food/fuel, utilities, or one-off impact events.</div>'}
function renderDebts(){$('#debts').innerHTML=state.debts.length?state.debts.map(x=>`<article class="card c-debt"><span class="ctop"><span>DEBT DRAGON</span><span>${x.apr?`${x.apr.toFixed(2)}% APR`:'APR unspecified'}</span></span><strong class="cname">${esc(x.name)}</strong><b class="camount">${fmt(x.balance)}</b><span class="cmeta"><span>${chunks(x.balance)}</span><span>due day ${x.dueDay}</span></span><div class="dragonbuttons"><button ${attrs({k:'balance',id:x.id})}>TUNE BODY<br>${fmt(x.balance)}</button><button ${attrs({k:'minimum',id:x.id})}>TUNE MINIMUM<br>${fmt(x.minPayment)}</button></div></article>`).join(''):'<div class="empty">No dragons placed. Add a debt account to make its full mass and monthly bite visible.</div>'}
function renderDesires(){$('#desires').innerHTML=state.desires.length?state.desires.map(x=>{let p=x.target?clamp(x.saved/x.target*100,0,100):0;return`<button class="card c-invest" ${attrs({k:'saved',id:x.id})}><span class="ctop"><span>TRACKED DESIRE</span><span>${Math.round(p)}%</span></span><strong class="cname">${esc(x.name)}</strong><b class="camount">${fmt(x.saved)} <small>/ ${fmt(x.target)}</small></b><span class="bar"><i style="width:${p}%"></i></span><span class="cmeta"><span>${esc(x.notes||'A bounded place for something alive.')}</span></span><span class="hint">TAP TO TUNE ↔</span></button>`}).join(''):'<div class="empty">No sanctioned life tracks yet. Books, tools, toys, travel, food pleasures, and weirdness can all have a bounded address here.</div>'}
function render(){renderStatus();renderBody();renderTime();renderTerritories();renderExpenses();renderDebts();renderDesires();save()}
function open(id){if(sheet&&sheet!==id)close(sheet,false);sheet=id;$(`#${id}`).classList.add('open');$(`#${id}`).setAttribute('aria-hidden','false');$('#backdrop').hidden=false;document.body.classList.add('sheetopen')}
function close(id=sheet,clear=true){if(!id)return;$(`#${id}`).classList.remove('open');$(`#${id}`).setAttribute('aria-hidden','true');if(clear&&id==='quickSheet')quick=null;if(clear&&id==='daySheet')dayKey=null;if(clear&&id==='editorSheet')editor=null;if(sheet===id)sheet=null;if(!sheet){$('#backdrop').hidden=true;document.body.classList.remove('sheetopen')}}
function preview(v,c){return Array.from({length:Math.min(cells(v),180)},()=>`<i style="--c:${color[c]||color.cash}"></i>`).join('')}
function syncQuick(v){qDraft=nn(v);let m=meta(quick);$('#quickInput').value=qDraft;$('#quickReadout').textContent=fmt(qDraft);$('#quickDialValue').textContent=`${fmt(qDraft)} · ${chunks(qDraft)}`;$('#quickPreview').innerHTML=preview(qDraft,m.c)}
function openQuick(t){let m=meta(t);if(!m)return;quick=t;$('#quickKicker').textContent=m.kicker;$('#quickTitle').textContent=m.title;$('#quickDesc').textContent=m.desc;$('#quickExactLabel').textContent=m.label;$('#quickQuarterMinus').textContent=fmt(quarter());$('#quickQuarterPlus').textContent=fmt(quarter());$('#quickInput').step=quarter();$('#quickDetails').textContent=t.k==='territory'?'ADD / DETAILS':'DETAILS';syncQuick(get(t));open('quickSheet')}
function applyQuick(){if(!quick)return;set(quick,$('#quickInput').value);close('quickSheet');render()}
function details(){if(!quick)return;let t=quick;close('quickSheet');if(t.k==='territory')edit('asset',null,{type:t.id});else edit(meta(t).edit,t.id)}
function syncDay(v){dayDraft=nn(v);$('#dayInput').value=dayDraft;$('#dayReadout').textContent=dayDraft?fmt(dayDraft):'NO GOAL';$('#dayDialValue').textContent=`${fmt(dayDraft)} · ${chunks(dayDraft)}`}
function openDay(k){dayKey=k;let d=parse(k);$('#dayTitle').textContent=`${wk(d)} · ${label(d)}`;$('#dayQuarterMinus').textContent=fmt(quarter());$('#dayQuarterPlus').textContent=fmt(quarter());$('#dayInput').step=quarter();syncDay(state.calendarGoals[k]||0);let es=events().filter(x=>iso(x.date)===k);$('#dayEvents').innerHTML=es.length?es.map(x=>`<button class="dayevent ${x.kind}" data-edit="${x.source}" data-id="${x.id}"><span>${esc(x.name)} · ${esc(x.meta)}</span><b>${fmt(x.amount)}</b></button>`).join(''):'<p class="dayempty">No financial events on this day yet. That is an invitation, not an error.</p>';open('daySheet')}
function saveDay(){if(!dayKey)return;let x=nn($('#dayInput').value);if(x)state.calendarGoals[dayKey]=x;else delete state.calendarGoals[dayKey];state.isDemo=false;close('daySheet');render()}
function field(label,name,type='text',v='',opts={}){let f=opts.full?'full':'';let attrs=opts.attrs||'';if(type==='select')return`<label class="${f}"><span>${label}</span><select name="${name}" ${attrs}>${opts.choices.map(x=>`<option value="${x[0]}" ${String(x[0])===String(v)?'selected':''}>${x[1]}</option>`).join('')}</select></label>`;if(type==='textarea')return`<label class="${f}"><span>${label}</span><textarea name="${name}" ${attrs}>${esc(v)}</textarea></label>`;return`<label class="${f}"><span>${label}</span><input type="${type}" name="${name}" value="${esc(v)}" ${attrs}/></label>`}
function record(type,id){let a=type==='asset'?state.assets:type==='expense'?state.expenses:type==='debt'?state.debts:state.desires;return id?a.find(x=>x.id===id):null}
function edit(type,id=null,preset={}){editor={type,id,preset};let x=record(type,id),title={asset:'money object',expense:'obligation',debt:'debt dragon',desire:'sanctioned life track'}[type];$('#editorKicker').textContent=id?`EDIT ${title.toUpperCase()}`:`NEW ${title.toUpperCase()}`;$('#editorTitle').textContent=id?`Edit ${title}`:`Place a ${title}`;$('#deleteBtn').hidden=!id;let h='';if(type==='asset'){x=x||{name:'',type:preset.type||'cash',amount:'',expectedDate:preset.expectedDate||'',confidence:100,notes:''};h=field('Name','name','text',x.name,{full:true,attrs:'required'})+field('Liquidity territory','type','select',x.type,{choices:ORDER.map(k=>[k,A[k][0]])})+field('Amount','amount','number',x.amount,{attrs:'min="0" step="1" required'})+field('Expected landing date','expectedDate','date',x.expectedDate)+field('Pipeline confidence %','confidence','number',x.confidence,{attrs:'min="0" max="100" step="1"'})+field('Notes','notes','textarea',x.notes,{full:true})}if(type==='expense'){x=x||{name:'',amount:'',cadence:preset.cadence||'monthly',type:preset.type||'essential',dueDay:today().getDate(),dueDate:preset.dueDate||'',notes:''};h=field('Name','name','text',x.name,{full:true,attrs:'required'})+field('Amount','amount','number',x.amount,{attrs:'min="0" step="1" required'})+field('Category','type','select',x.type,{choices:Object.entries(E).map(([k,v])=>[k,v[0]])})+field('Cadence','cadence','select',x.cadence,{choices:[['monthly','Monthly recurring'],['oneoff','One-off date']]})+field('Monthly due day','dueDay','number',x.dueDay,{attrs:'min="1" max="31" step="1"'})+field('One-off due date','dueDate','date',x.dueDate,{full:true})+field('Notes','notes','textarea',x.notes,{full:true})}if(type==='debt'){x=x||{name:'',balance:'',minPayment:'',dueDay:today().getDate(),apr:'',notes:''};h=field('Name','name','text',x.name,{full:true,attrs:'required'})+field('Current balance','balance','number',x.balance,{attrs:'min="0" step="1" required'})+field('Monthly minimum','minPayment','number',x.minPayment,{attrs:'min="0" step="1" required'})+field('Due day','dueDay','number',x.dueDay,{attrs:'min="1" max="31" step="1"'})+field('APR','apr','number',x.apr,{attrs:'min="0" step="0.01"'})+field('Notes','notes','textarea',x.notes,{full:true})}if(type==='desire'){x=x||{name:'',target:'',saved:'',notes:''};h=field('Name','name','text',x.name,{full:true,attrs:'required'})+field('Target amount','target','number',x.target,{attrs:'min="0" step="1" required'})+field('Already reserved','saved','number',x.saved,{attrs:'min="0" step="1"'})+field('Why this matters','notes','textarea',x.notes,{full:true})}$('#editorFields').innerHTML=h;open('editorSheet')}
function saveEdit(ev){ev.preventDefault();if(!editor)return;let {type,id}=editor,o=Object.fromEntries(new FormData($('#editorForm')).entries()),old=record(type,id),x;if(type==='asset')x={id:id||uid('a'),name:o.name.trim()||'Untitled money',type:A[o.type]?o.type:'cash',amount:nn(o.amount),expectedDate:o.expectedDate||'',confidence:clamp(n(o.confidence,100),0,100),notes:o.notes.trim()};if(type==='expense')x={id:id||uid('e'),name:o.name.trim()||'Untitled obligation',amount:nn(o.amount),cadence:o.cadence==='oneoff'?'oneoff':'monthly',type:E[o.type]?o.type:'essential',dueDay:clamp(Math.round(n(o.dueDay,1)),1,31),dueDate:o.dueDate||'',notes:o.notes.trim()};if(type==='debt')x={id:id||uid('d'),name:o.name.trim()||'Untitled dragon',balance:nn(o.balance),minPayment:nn(o.minPayment),dueDay:clamp(Math.round(n(o.dueDay,1)),1,31),apr:nn(o.apr),notes:o.notes.trim()};if(type==='desire')x={id:id||uid('l'),name:o.name.trim()||'Untitled track',target:nn(o.target),saved:nn(o.saved),notes:o.notes.trim()};let arr=type==='asset'?state.assets:type==='expense'?state.expenses:type==='debt'?state.debts:state.desires,i=arr.findIndex(y=>y.id===x.id);if(i>=0)arr[i]=x;else arr.push(x);if(type==='asset'){if(old?.type)delete state.territoryTotals[old.type];delete state.territoryTotals[x.type]}state.isDemo=false;close('editorSheet');render()}
function del(){if(!editor?.id)return;let x=record(editor.type,editor.id);if(!x||!confirm(`Delete “${x.name}” from the board?`))return;let a=editor.type==='asset'?state.assets:editor.type==='expense'?state.expenses:editor.type==='debt'?state.debts:state.desires;a.splice(a.findIndex(y=>y.id===x.id),1);if(editor.type==='asset')delete state.territoryTotals[x.type];state.isDemo=false;close('editorSheet');render()}
function settings(){ $('#taskPayoutInput').value=state.settings.taskPayout;$('#tileInput').value=tile();$('#horizonInput').value=state.settings.forecastDays;open('settingsSheet') }
function saveSettings(e){e.preventDefault();state.settings.taskPayout=nn($('#taskPayoutInput').value);state.settings.chunkSize=clamp(Math.round(n($('#tileInput').value,100)/100)*100,100,2000);state.settings.forecastDays=clamp(Math.round(n($('#horizonInput').value,28)/7)*7,14,84);state.isDemo=false;close('settingsSheet');render()}
function exportBoard(){let b=new Blob([JSON.stringify({app:'CHUNK // SOLVENCY',version:VERSION,exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`chunk-solvency-backup-${iso(today())}.json`;document.body.append(a);a.click();a.remove();URL.revokeObjectURL(u)}
function importBoard(file){if(!file)return;let r=new FileReader;r.onload=()=>{try{let x=JSON.parse(r.result);state=norm(x.state||x);state.isDemo=false;render();alert('Board imported. This browser now holds the imported local board.')}catch(e){alert('That file was not a valid CHUNK board backup.')}};r.readAsText(file)}
function begin(e,type){e.preventDefault();drag={type,x:e.clientX};e.currentTarget.setPointerCapture?.(e.pointerId)}function move(e){if(!drag)return;e.preventDefault();let z=Math.trunc((e.clientX-drag.x)/18);if(!z)return;drag.x+=z*18;if(drag.type==='q')syncQuick(qDraft+z*quarter());else syncDay(dayDraft+z*quarter())}function end(){drag=null}
function click(e){let x=e.target.closest('[data-close]');if(x){close(x.dataset.close);return}x=e.target.closest('[data-add]');if(x){edit(x.dataset.add);return}x=e.target.closest('[data-day]');if(x){openDay(x.dataset.day);return}x=e.target.closest('[data-edit]');if(x){close('daySheet');edit(x.dataset.edit,x.dataset.id);return}x=e.target.closest('[data-k]');if(x){openQuick({k:x.dataset.k,id:x.dataset.id});return}}
function keys(e){if(e.key==='Escape')close();if(e.target===$('#quickDial')){if(e.key==='ArrowLeft')syncQuick(qDraft-quarter());if(e.key==='ArrowRight')syncQuick(qDraft+quarter())}if(e.target===$('#dayDial')){if(e.key==='ArrowLeft')syncDay(dayDraft-quarter());if(e.key==='ArrowRight')syncDay(dayDraft+quarter())}}
function init(){ $('#exportBtn').onclick=exportBoard;$('#importBtn').onclick=()=>$('#importInput').click();$('#importInput').onchange=e=>importBoard(e.target.files[0]);$('#settingsBtn').onclick=settings;$('#taskBtn').onclick=settings;$('#cleanBtn').onclick=()=>{if(confirm('Start a clean board?')){state=blank();render()}};$('#loadDemoBtn').onclick=()=>{if(confirm('Replace this local board with demo terrain? Export first if you want a backup.')){state=demo();render()}};$('#resetBtn').onclick=()=>{if(confirm('Erase all local board data?')){state=blank();render()}};$('#quickInput').oninput=e=>syncQuick(e.target.value);$('#quickMinus').onclick=()=>syncQuick(qDraft-quarter());$('#quickPlus').onclick=()=>syncQuick(qDraft+quarter());$('#quickApply').onclick=applyQuick;$('#quickDetails').onclick=details;$('#dayInput').oninput=e=>syncDay(e.target.value);$('#dayMinus').onclick=()=>syncDay(dayDraft-quarter());$('#dayPlus').onclick=()=>syncDay(dayDraft+quarter());$('#clearGoal').onclick=()=>syncDay(0);$('#saveDay').onclick=saveDay;$('#addIncomeDay').onclick=()=>{let k=dayKey;close('daySheet');edit('asset',null,{type:'pipeline',expectedDate:k})};$('#addExpenseDay').onclick=()=>{let k=dayKey;close('daySheet');edit('expense',null,{cadence:'oneoff',dueDate:k})};$('#editorForm').onsubmit=saveEdit;$('#deleteBtn').onclick=del;$('#settingsForm').onsubmit=saveSettings;$('#backdrop').onclick=()=>close();$('#quickDial').onpointerdown=e=>begin(e,'q');$('#dayDial').onpointerdown=e=>begin(e,'d');window.addEventListener('pointermove',move,{passive:false});window.addEventListener('pointerup',end);window.addEventListener('pointercancel',end);document.addEventListener('click',click);document.addEventListener('keydown',keys);document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));render()}
// All helper functions and consts are initialized now; only now is it safe to deserialize or create the board.
state=load();
document.addEventListener('DOMContentLoaded',init);
